import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ['latin'], variable: '--font-inter'});



export const metadata: Metadata = {
  title: "first Next.js app",
  description: "Generated by Afroozi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased h-full m-0 p-0 bg-red-500`}
      >
        {children}
      </body>
    </html>
  );
}
